"""Builds the artifacts the instance pulls from S3 on boot.

Three things live under s3://<bucket>/bootstrap/:
  agent.tar.gz  -- the instance-side scripts (pickaxe/agent/)
  pickaxe.env   -- rendered config.yaml, as shell variables
  seed/serverdata.tar.gz -- optional world to restore on first boot

The EC2 UserData is deliberately kept minimal and constant: it only embeds the
bucket and region. CloudFormation replaces an instance whenever UserData
changes, which would wipe the root volume -- so config changes must flow
through S3, never through UserData.
"""

from __future__ import annotations

import io
import shlex
import tarfile
from pathlib import Path

from .config import Config

AGENT_DIR = Path(__file__).parent / "agent"

# Excluded from the world seed: regenerated on the server, or huge and useless.
SEED_EXCLUDES = {
    "logs",
    "crash-reports",
    "cache",
    "libraries",
    "versions",
    ".git",
    "__pycache__",
}

USER_DATA = r"""#!/bin/bash
# Pickaxe bootstrap. Runs once, on first boot. Keep this file byte-stable:
# any change forces CloudFormation to replace the instance.
set -euo pipefail
exec > >(tee -a /var/log/pickaxe-userdata.log) 2>&1
echo "=== pickaxe userdata $(date -u +%FT%TZ) ==="

PICKAXE_BUCKET={bucket}
PICKAXE_REGION={region}
export AWS_DEFAULT_REGION="$PICKAXE_REGION"

export DEBIAN_FRONTEND=noninteractive
for attempt in 1 2 3 4 5; do
  apt-get update -y && break || sleep 15
done
apt-get install -y --no-install-recommends curl unzip tar ca-certificates jq python3

if ! command -v aws >/dev/null 2>&1; then
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o /tmp/awscliv2.zip
  unzip -q -o /tmp/awscliv2.zip -d /tmp
  /tmp/aws/install --update
  rm -rf /tmp/aws /tmp/awscliv2.zip
fi

# The instance profile can take a few seconds to become usable.
for attempt in $(seq 1 30); do
  aws sts get-caller-identity >/dev/null 2>&1 && break
  sleep 5
done

mkdir -p /etc/pickaxe /opt/pickaxe /var/lib/pickaxe
aws s3 cp "s3://$PICKAXE_BUCKET/bootstrap/pickaxe.env" /etc/pickaxe/pickaxe.env
aws s3 cp "s3://$PICKAXE_BUCKET/bootstrap/agent.tar.gz" /tmp/agent.tar.gz
tar -xzf /tmp/agent.tar.gz -C /opt/pickaxe
chmod +x /opt/pickaxe/*.sh
rm -f /tmp/agent.tar.gz

/opt/pickaxe/install.sh
echo "=== pickaxe userdata done $(date -u +%FT%TZ) ==="
"""


def render_user_data(cfg: Config, bucket: str) -> str:
    return USER_DATA.format(bucket=shlex.quote(bucket), region=shlex.quote(cfg.aws.region))


def render_env(cfg: Config, bucket: str) -> str:
    values = {
        "PICKAXE_SERVER": cfg.server.name,
        "PICKAXE_BUCKET": bucket,
        "PICKAXE_REGION": cfg.aws.region,
        "PICKAXE_MC_VERSION": cfg.minecraft.version,
        "PICKAXE_RAM_GB": cfg.minecraft.ram_gb,
        "PICKAXE_PORT": cfg.minecraft.port,
        "PICKAXE_MOTD": cfg.minecraft.motd,
        "PICKAXE_BACKUP_INTERVAL": cfg.backup.interval_minutes,
        "PICKAXE_BACKUP_KEEP": cfg.backup.keep,
        "PICKAXE_IDLE_ENABLED": "true" if cfg.idle.enabled else "false",
        "PICKAXE_IDLE_MINUTES": cfg.idle.shutdown_after_minutes,
        "PICKAXE_BOOT_GRACE": cfg.idle.boot_grace_minutes,
    }
    lines = ["# Generated by `pickaxe up` from config.yaml. Do not edit on the instance."]
    lines += [f"{key}={shlex.quote(str(value))}" for key, value in values.items()]
    return "\n".join(lines) + "\n"


def build_agent_bundle() -> bytes:
    """tar.gz of pickaxe/agent, with the executable bit preserved."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for path in sorted(AGENT_DIR.iterdir()):
            if path.name.startswith(".") or path.name == "__pycache__":
                continue
            info = tar.gettarinfo(str(path), arcname=path.name)
            info.mode = 0o755 if path.suffix in (".sh", ".py") else 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            info.mtime = 0
            with path.open("rb") as handle:
                tar.addfile(info, handle)
    return buf.getvalue()


def build_world_seed(world_dir: Path, destination: Path) -> Path:
    """tar.gz the user's existing server directory, to be unpacked over /opt/minecraft.

    Streamed to a file rather than held in memory: a long-running world is
    routinely several GB, which is both too much RAM and past the 5 GB ceiling
    on a single-part S3 upload.
    """

    def keep(info: tarfile.TarInfo) -> tarfile.TarInfo | None:
        if set(info.name.split("/")) & SEED_EXCLUDES:
            return None
        info.uid = info.gid = 0
        info.uname = info.gname = "root"
        return info

    with tarfile.open(str(destination), mode="w:gz") as tar:
        for path in sorted(world_dir.iterdir()):
            if path.name in SEED_EXCLUDES or path.name.startswith("."):
                continue
            tar.add(str(path), arcname=path.name, filter=keep)
    return destination
